import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  mainContainer: {justifyContent: 'center', flex: 1, backgroundColor: '#000'},
  imageOuterView: {
    flex: 1,
    height: '50%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  backArrow: {
    position: 'absolute',
    zIndex: 1,
    top: Platform.OS === 'android' ? 20 : 60,
    left: 16,
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  backImg: {height: 16, width: 16},
  img: {width: '95%', height: 200},
  playbackContainer: {
    flex: 1,
    // flexDirection: 'row',
  },
  titleTrack: {
    fontSize: 20,
    color: '#FFF',
    alignItems: 'flex-start',
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
    lineHeight: 30,
  },
  seekbar: {
    width: '100%',
  },
  controlsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 50,
    alignItems: 'center',
  },
  playPause: {
    height: 70,
    width: 70,
    borderRadius: 35,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  prevNext: {
    height: 40,
    width: 40,
    borderRadius: 20,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 50,
    marginLeft: 50,
  },
  icon: {height: 20, width: 20},
  disabled: {opacity: 0.4},
});
